### ISSUE TITLE
git-integration-api load configuration from env variables

### ISSUE THREAD

**Issue by slivkamiro** [curityio/idsvr-gitops-configuration-management#9]
Hi Curity,
first I want to thank you for this project.
I'd like to suggest adding a possibility to override configuration of git-integration-api service with env variables. This would be really helpful when deploying to k8s (and for example injecting secrets using [external secrets operator](https://external-secrets.io/latest/)).
Would you be interested in adding such feature here?

**Comment by gary-archer** [comment]
Thanks for the feedback - we added a [small PR here](https://github.com/curityio/idsvr-gitops-configuration-management/pull/10). Let us know if this works for you and we will merge it.

**Comment by slivkamiro** [comment]
Awesome, yes that works, thanks :)
